// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRABALHOFINALDOPI.Data;

#nullable disable

namespace TRABALHOFINALDOPI.Migrations
{
    [DbContext(typeof(TRABALHOFINALDOPIContext))]
    [Migration("20230406140950_T_Pedido")]
    partial class T_Pedido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.DoarOuReceber", b =>
                {
                    b.Property<int>("DoarOuReceberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoarOuReceberId"), 1L, 1);

                    b.Property<string>("Celular")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OngId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<bool>("QuerDoar")
                        .HasColumnType("bit");

                    b.Property<bool>("QuerReceber")
                        .HasColumnType("bit");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("DoarOuReceberId");

                    b.HasIndex("OngId");

                    b.HasIndex("PedidoId");

                    b.ToTable("DoarOuReceber");
                });

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.Ong", b =>
                {
                    b.Property<int>("OngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OngId"), 1L, 1);

                    b.Property<string>("Nome_Ong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OngId");

                    b.ToTable("Ong");
                });

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"), 1L, 1);

                    b.Property<string>("Nome_Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.DoarOuReceber", b =>
                {
                    b.HasOne("TRABALHOFINALDOPI.Models.Ong", "Nome_Ong")
                        .WithMany("DoarOuRecebers")
                        .HasForeignKey("OngId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TRABALHOFINALDOPI.Models.Pedido", "Nome_Item")
                        .WithMany("DoarOuRecebers")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nome_Item");

                    b.Navigation("Nome_Ong");
                });

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.Ong", b =>
                {
                    b.Navigation("DoarOuRecebers");
                });

            modelBuilder.Entity("TRABALHOFINALDOPI.Models.Pedido", b =>
                {
                    b.Navigation("DoarOuRecebers");
                });
#pragma warning restore 612, 618
        }
    }
}
